### ISSUE TITLE
Quotes and comment modifiers should be configurable

### ISSUE THREAD

**Issue by CoenraadS** [CoenraadS/BracketPair#11]
Current implementation could be done more generically also

**Comment by Arithmeticae** [comment]
Agreed, and possibly by language.

You're currently missing the '#' for inline python comments, which leads to interesting things when using 
apostrophes in the comment.

![image](https://cloud.githubusercontent.com/assets/15927569/23026669/fc4b5f74-f42f-11e6-91d5-92afaf2b0d25.png)

**Comment by CoenraadS** [comment]
Yes, ideally I want to get this automatically from VSCode, and not make the user configure anything. 

Feel free to add a thumbs up to the issue: https://github.com/Microsoft/vscode/issues/20735

**Comment by CoenraadS** [comment]
@Arithmeticae 

I hardcoded some basic Python support in v0.7.5 for now since its a popular language, so you can try to see if its any better now.

**Comment by Arithmeticae** [comment]
Great, I'm giving it a go now and I'll let you know if I see anything fishy.

So far it looks good.

**Comment by pr-yemibedu** [comment]
Hello,
 Would you be able to at least hard code the comment styles for the top ten programming languages or some more of the top 6 unique comment styles? I think the principle techniques you used so far could working for other kinds. Thank you. Good day.

https://en.wikipedia.org/wiki/Comment_(computer_programming)#Examples

http://spectrum.ieee.org/static/interactive-the-top-programming-languages

**Comment by CoenraadS** [comment]
@pr-yemibedu 

Most popular languages are c-based, which share similar commenting styles. Do you have any specific request?

**Comment by CoenraadS** [comment]
@pr-yemibedu 

I am not against adding more support. I'm a bit afraid that by implemented support for languages I am not familiair with, my extension might only work for the most basic examples, but break in all sorts of edge cases. On the other hand its not much work for me to at least give it a shot.

**Comment by CoenraadS** [comment]
@pr-yemibedu 

I added experimental support for the following languages:

- python
- typescript
- javascript  
- c  
- cpp  
- csharp  
- java  
- php  
- ruby  
- r

Let me know if you would like to see more, or if you run into any issues.

**Comment by pr-yemibedu** [comment]
Hello,
 Are these just the code comments like (//) or also doc comments like (///)? I think the list you linked to is a great one. A number of these have an overlapping influence and so if you just make sure your notes and documentation reflect your effort, you probably won't have many requests or complaints. Some languages in the list have:
https://en.wikipedia.org/wiki/Docstring support.
and some like swift support embed comments. Best of luck. Good day.

**Comment by CoenraadS** [comment]
@pr-yemibedu 

I didn't explicitly support them, but the nice thing about those types of comments is that they are supported implicitly by the logic. Because doc strings are in groups of three, the logic just goes `open`, `close`, `open`

So they should work.

**Comment by pr-yemibedu** [comment]
Hello,
 So up for request is comment support for F#/Ocaml. I know F# is on the one linked list you gave. Thank you. Good day.

**Comment by CoenraadS** [comment]
Hello

Currently my logic cannot support F# triple comments, I will keep looking into it incase it might be possible without me having to make large changes.

![image](https://cloud.githubusercontent.com/assets/5593825/23531115/2369f69e-ffa5-11e6-8aa0-350836070e92.png)

**Comment by pr-yemibedu** [comment]
Hello,
 I actually have never yet used them. I would be happy with the progress. I did remember you said triple comment slash was not a problem. Maybe that has a different solver to do skipping. From after, it looks like:
""
"\<book author=" Milton, John
" title="
Paradise Lost
"\>"
""
I wonder if you can have a roaming toggle in that case that will set when it finds the starting triplet can stops after. Would you be able to tell me the part of the code that tracks the different string types? Thank you. Good day.

**Comment by CoenraadS** [comment]
@pr-yemibedu 

Yes triple quotes for things like js-doc were supported. But the logic behind them is different from f# tripple comments, because f# ignores single comments inside the triple comments.

Anyway, I just tested and it seems to work. https://github.com/CoenraadS/BracketPair/commit/ea4f0de552bb6399c7f75f089551ea27642e33ee

**Comment by pr-yemibedu** [comment]
Hello,
 Actually I was not giving an example, I was breaking apart you example into the notion of when would a parser have an issue. I think your implementation really is simple and gets the job done. It follows standard pattern matching style (more specific -> more generic).

I only am curious as two why it looks like:

`` else if (settings.languageID === "fsharp")
``
``        {
``
``            this.scopes.push(tripleQuoteBlock);
``
``            this.scopes.push(roundBracketCommentBlock);
``
``            this.scopes.push(singleQuoteBlock);
``
``            this.scopes.push(doubleForwardslashComment);
``
``        }
``
instead of:
`` else if (settings.languageID === "fsharp")
``
``        {
``
``            this.scopes.push(tripleQuoteBlock);
``
``            this.scopes.push(doubleQuoteBlock);
``
``            this.scopes.push(singleQuoteBlock);
``
``            this.scopes.push(roundBracketCommentBlock);
``
``            this.scopes.push(doubleForwardslashComment);
``
``        }
``
and you can have an extra function to reduce some lines of code:
``    function dsQuoteBlock(scope)
``
``    {
``
``            scope.push(doubleQuoteBlock);
``
``            scope.push(singleQuoteBlock);
``
``    }
``
can turn two lines into one:
``    dsQuoteBlock(this.scope);
``
 Thank you. Good day.

**Comment by CoenraadS** [comment]
@pr-yemibedu 

Good catch, I forgot to add the doubleQuotes.

I still might need to change some things up though

`val foo : x:'a -> 'a` will break my single quote parsing..

**Comment by pr-yemibedu** [comment]
Hello,
 You can also have an apostrophe and part of a binding name:
``    let x = 1
``
``    let x' = 2
``
``    let x'' = 3
``
that is valid it is also used to wrap a single character in the language. you may want to change the naming from tripleQuote to tripleDoubleQuote. F# would also need doubleBacktickQuoteBlock created because that is also valid for a binding name:
``    let ` `x ()` ` = 3 // assume no space between each ` ` pair in code. markdown limitation
``
so it seems that there would need to be a way to have a constraint for pattern blocks. Similar to regex constraints {m, n} to have:
``    const charSingleQuoteBlock = new ScopePattern(singleQuote, singleQuote, {isSingle = true});
``
or
``    const charSingleQuoteBlock = new ScopePattern(singleQuote, singleQuote, {min = 1, max = 1});
``
I can not think of another way. Hopefully it is less of a hack that it may first look. Since you can build this as an options object, you can at least reduce to the number of functions that will need to check for the value. Your hard work is appreciated. Thank you. Good day.
