### ISSUE TITLE
[Future Development] Can we help in any way?

### ISSUE THREAD

**Issue by BtM909** [CoenraadS/BracketPair#60]
> Note: This extension has grown beyond its initial requirements and needs a rewrite for better language support..
Do you already have an idea what needs to be done? Maybe it's something we can already start contributing to. 

This extension rocks!

**Comment by CoenraadS** [comment]
Sure 👍  Although a rewrite might be better of as a new extension.

Because my language support is so hacky, I was thinking about using a third party library, such as [PrismJS](http://prismjs.com/). Another extension is already using this library, and can be used as reference: https://github.com/rafamel/subtle-brackets
